### PR TITLE
Update to newest version of phantomas

### PR DESCRIPTION
**Pull request by gfdickinson**

### CODE REVIEW

**Comment by stefanjudis** [comment]
@gfdickinson 

That's looking good. I think it might pass now. ;)

**Comment by stefanjudis** [comment]
Cool - thanks. I'm happy to take it. 

Thanks again. :)

**Comment by gfdickinson** [comment]
my pleasure...I am definitely going to be using this for my project and hope to contribute more.

**Comment by stefanjudis** [comment]
Glad to here that. :bowtie: 

I'm way too busy the last months and am more than happy about every contribution.
Just in case you want to become collaborator, let me know. ;)

**Pull request merged**
